In [1]:
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 15 14:49:19 2019

@author: krish.naik
"""

# Face Recognition

# Importing the libraries
from PIL import Image
import tensorflow as tf
from tensorflow.keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from tensorflow.keras.models import load_model
import numpy as np

from tensorflow.keras.preprocessing import image
model = load_model('/Users/vikaspuri/ArtificialIntelligence/MachineLearningApplications/FaceRecognisation/facefeatures_new_model.h5')

# Loading the cascades
face_cascade = cv2.CascadeClassifier('/Users/vikaspuri/ArtificialIntelligence/MachineLearningApplications/FaceRecognisation/haarcascade_frontalface_default.xml')

def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
    #gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

# Doing some Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    #canvas = detect(gray, frame)
    #image, face =face_detector(frame)
    
    face=face_extractor(frame)
    print(face)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
           #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
                    #Our keras model used a 4D tensor, (images x height x width x channel)
                    #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][1]>0.5):
            name='Vikas'
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()
for i in range(10):    # maybe 5 or more
    cv2.waitKey(1)

       



None
[[[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [ 15  12  16]
  ...
  [ 60  81  81]
  [ 61  79  82]
  [  0 255 255]]

 ...

 [[  0 255 255]
  [  0 255 255]
  [ 70  68  75]
  ...
  [ 34  49  53]
  [ 32  46  52]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [ 71  69  76]
  ...
  [ 36  52  55]
  [ 32  46  52]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]]


TypeError: Value passed to parameter 'input' has DataType uint8 not in list of allowed values: float16, bfloat16, float32, float64